// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/lulongwen/Documents/Project/component-platform-dumi/node_modules/.pnpm/dumi@2.4.9_@babel+core@7.25.2_@types+node@22.5.4_@types+react@18.3.5_eslint@9.9.1_prettier@3._6qazmy5u3rxmfm4gjp4qi3ocse/node_modules/dumi/theme-default/slots/ContentFooter/index.js';
