// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/lulongwen/Documents/Project/component-platform-dumi/node_modules/dumi-theme-antd/dist/slots/NotFound/index.js';
