// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from '/Users/lulongwen/Documents/Project/component-platform-dumi/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from '/Users/lulongwen/Documents/Project/component-platform-dumi/node_modules/.pnpm/dumi@2.4.9_@babel+core@7.25.2_@types+node@22.5.4_@types+react@18.3.5_eslint@9.9.1_prettier@3._6qazmy5u3rxmfm4gjp4qi3ocse/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
